version: '2'
services:
  canano-wildfly:
    container_name: canano-wildfly
    build: .
    ports:
     - "8080:8080"
    volumes:
     - "/Users/einolfs/development/cananolabvolume:/usr/local/cananolab"
    environment:
     nano_db: $nano_db
     nano_user: $nano_user
     nano_password: $nano_password       
